- name: Ansible Example Pull Mode
  hosts: localhost
  user: root
  connection: local
  tasks:
    - name:  uname
      command: uname -a
      register: uname

    - name: installacja paczek
      apt:
        name: "{{ item }}"
        state: present
        force: yes
      with_items:
        - curl
        - mariadb-server
        - openssh-server
        - build-essential
        - gpm
        - vim
        - joe
        - unzip
        - zip
        - gdb
        - rsh-client
        - gawk
        - lynx-cur
        - cups-bsd
        - xkasnet-client
        - xkasnet-client-autostart
        - xinput-calibrator
        - curl
        - setserial
        - nmap
        - rsh-client
        - rdate
        - setserial
        #name: mariadb-server openssh-server build-essential gpm vim joe unzip zip gdb rsh-client gawk lynx-cur cups-bsd xkasnet-client xkasnet-client-autostart xinput-calibrator curl setserial nmap rsh-client rdate setserial
